# Generated by Django 2.1.5 on 2024-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240320_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(max_length=32),
        ),
    ]
